name: Deploying documentation

on:
  push:
    branches:
      - master
      - documentation

jobs:

  Deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: sudo apt-get install doxygen
    - run: sudo apt-get install graphviz
    - run: sudo apt-get install cmake
    - run: make doc_generation

    - name: Push git subdirectory as branch
      uses: s0/git-publish-subdir-action@develop

      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: html 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAN: true
